import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';
import 'package:furnace/domain/services/cognitive/cognitive_graph.dart';
import 'package:furnace/domain/services/cognitive/fast_engine.dart';

/// Conformance test for the Dart port of MindNet's **fast layer** (tierB).
///
/// The expectation source is the `tierB` block of
/// `test/fixtures/mindnet_vectors.json`, generated by MindNet's own
/// `tools/conformance.js` from the real JS engine (the file records
/// `generated_from.commit`). `docs/MINDNET_CONTRACT.md` §6.2 fixes how to read
/// it, and this test follows that to the letter:
///
/// * set/enum fields (`kind`, `admitted`, `focus`, `outcompeted`, `conscious`,
///   `subconscious`, `states[].state_after`, `round`, `cycle_ticks`) are
///   compared **exactly**;
/// * floats are compared with `rel <= 1e-12` (`abs <= 1e-15` as the floor), and
///   a miss is treated as a real implementation difference, not swept into a
///   loose tolerance;
/// * values the generator publishes already rounded are rounded here the same
///   way before comparing (`dar_used` and the raw `ls`/`al`/`ms` of a drive
///   term are published un-rounded, so they are compared raw).
///
/// Beyond the diff, the semantic checks the port could get wrong while still
/// "looking right" are pinned separately: the exact integral (not Euler), the
/// starts being held at `a = 1`, the two-level capacity, the ignition sigmoid,
/// and the goal bias skipping the target itself.
///
/// ## What B01 can and cannot prove (read this before citing it)
///
/// B01's five round snapshots are **field-for-field identical**, and every
/// `round` field is 1. That is real MindNet behaviour, not a copy/paste slip:
/// the target lights up in round 1, `_all_targets_active()` then trips
/// `_stop(ALL_TARGETS_REACHED)`, and every later `step()` returns before
/// touching `_lastRound` (`E:\Document\MindNet\src\v2\engine.js` L139-140 no-op
/// return, L142 counter, L282 stop check, L404-409 "ever activated counts as
/// reached"). A mutation test makes the consequence concrete: replacing rounds
/// 2..5 with copies of round 1 yields zero mismatches under the fixture's own
/// tolerances.
///
/// So B01 proves the **first round's** fields bit-for-bit, plus the stop
/// semantics ("stopped means the snapshot is not rebuilt"). It does **not**
/// prove that the state machine advances round over round, and no summary of
/// this port should claim that from B01.
///
/// The gap is closed from the other side by the multi-round scenario below: it
/// lives in `test/fixtures/mindnet_tierb_diagnosis.json`
/// (`scenarios.multiround_progression`), puts the goal at the end of a long weak
/// chain so it does **not** light in round 1, and the engine really executes six
/// rounds before the stop. Those expectations come from the real JS as well,
/// through the same read-only generator:
///
/// ```
/// cd E:/FirsryOS/Memory/一THREADRIPPER一/class-productivity
/// node app/tool/gen_mindnet_tierb_diagnosis.cjs
/// ```
///
/// (The generator only `require`s MindNet's modules; it never writes there.)
void main() {
  final file = File('test/fixtures/mindnet_vectors.json');
  if (!file.existsSync()) {
    test('mindnet fast-layer conformance vectors', () {
      fail('missing ${file.path} - the contract requires the snapshot to be '
          'vendored into this repository (§6.2/§6.6)');
    });
    return;
  }

  final vectors = jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
  final tolerances = (vectors['tolerances'] as Map).cast<String, Object?>();
  final rel = (tolerances['rel'] as num).toDouble();
  final abs = (tolerances['abs'] as num).toDouble();
  final tierB = (vectors['tierB'] as List).cast<Map<String, Object?>>();
  final vector = tierB.firstWhere(
    (v) => v['id'] == 'B01-fast-layer-chain-5-rounds',
    orElse: () => throw StateError('B01 vector missing from the snapshot'),
  );

  final input = (vector['input'] as Map).cast<String, Object?>();
  final expected =
      ((vector['expected'] as Map)['rounds'] as List).cast<Map<String, Object?>>();

  Map<String, Object?> asMap(Object? value) =>
      (value as Map).cast<String, Object?>();

  /// Compares one published number.
  ///
  /// [rounded] mirrors the generator: values it runs through `round6` are
  /// compared after the same rounding, values it publishes raw are compared
  /// raw. Either way the contract's tolerance is the hard standard.
  void expectNumber(
    String where,
    double actual,
    num expectedValue, {
    required bool rounded,
  }) {
    final want = expectedValue.toDouble();
    final got = rounded ? FastEngine.round6(actual) : actual;
    final diff = (got - want).abs();
    final scale = want.abs() > 1 ? want.abs() : 1.0;
    final ok = diff <= abs || diff / scale <= rel;
    expect(
      ok,
      isTrue,
      reason: '$where: actual=$got (raw=$actual) expected=$want diff=$diff '
          '(rel=${diff / scale}, allowed rel=$rel abs=$abs)',
    );
  }

  /// Asserts the port produced exactly the published keys - no silent skips.
  void expectSameKeys(String where, Map<String, Object?> actual,
      Map<String, Object?> want) {
    expect(actual.keys.toSet(), want.keys.toSet(),
        reason: '$where: field set drifted');
  }

  /// Field-for-field comparison of one round snapshot against a published one.
  ///
  /// Shared by B01 and the multi-round scenario, so both are held to the same
  /// rules: set/enum fields exact, floats the generator rounded compared after
  /// the same `round6`, and the few values it publishes raw (`dar_used`, a drive
  /// term's `ls`/`al`/`ms`) compared raw.
  void compareRound(
    String id,
    FastRoundSnapshot snapshot,
    Map<String, Object?> want,
  ) {
    final got = snapshot.toJson();
    expectSameKeys(id, got, want);

    expect(got['round'], want['round'], reason: '$id: round');
    expect(got['cycle_ticks'], want['cycle_ticks'],
        reason: '$id: cycle_ticks');
    expectNumber(id, got['availability']! as double, want['availability']! as num,
        rounded: true);

    final gotDrive = asMap(got['drive']);
    final wantDrive = asMap(want['drive']);
    expectSameKeys('$id.drive', gotDrive, wantDrive);
    for (final entry in wantDrive.entries) {
      expectNumber('$id.drive[${entry.key}]',
          (gotDrive[entry.key]! as num).toDouble(), entry.value! as num,
          rounded: true);
    }

    final gotEdges = (got['drive_edges'] as List).cast<Map>();
    final wantEdges = (want['drive_edges'] as List).cast<Map>();
    expect(gotEdges, hasLength(wantEdges.length),
        reason: '$id: drive_edges count');
    for (var j = 0; j < wantEdges.length; j++) {
      final edgeId = '$id.drive_edges[$j]';
      final gotEdge = gotEdges[j].cast<String, Object?>();
      final wantEdge = wantEdges[j].cast<String, Object?>();
      expectSameKeys(edgeId, gotEdge, wantEdge);
      expect(gotEdge['from'], wantEdge['from'], reason: '$edgeId: from');
      expect(gotEdge['to'], wantEdge['to'], reason: '$edgeId: to');
      expect(gotEdge['edge_id'], wantEdge['edge_id'],
          reason: '$edgeId: edge_id');
      expect(gotEdge['kind'], wantEdge['kind'], reason: '$edgeId: kind');
      expect(gotEdge['module'], wantEdge['module'], reason: '$edgeId: module');
      // `ls`/`al`/`ms` are published raw, and are null for the terms that are
      // not in-edges (sub-threshold accumulation, module rewrites).
      for (final field in ['ls', 'al', 'ms']) {
        final gotValue = gotEdge[field];
        final wantValue = wantEdge[field];
        if (wantValue == null) {
          expect(gotValue, isNull, reason: '$edgeId: $field must be null');
          continue;
        }
        expectNumber(edgeId, gotValue! as double, wantValue as num,
            rounded: false);
      }
      expectNumber(edgeId, gotEdge['contribution']! as double,
          wantEdge['contribution']! as num,
          rounded: true);
    }

    final gotScores = asMap(got['scores']);
    final wantScores = asMap(want['scores']);
    expectSameKeys('$id.scores', gotScores, wantScores);
    for (final entry in wantScores.entries) {
      expectNumber('$id.scores[${entry.key}]',
          (gotScores[entry.key]! as num).toDouble(), entry.value! as num,
          rounded: true);
    }

    // Set-valued and enum fields: exact, per the contract's table.
    expect(got['admitted'], want['admitted'], reason: '$id: admitted');
    expect(got['focus'], want['focus'], reason: '$id: focus');
    expect(got['outcompeted'], want['outcompeted'],
        reason: '$id: outcompeted');
    expect(got['conscious'], want['conscious'], reason: '$id: conscious');
    expect(got['subconscious'], want['subconscious'],
        reason: '$id: subconscious');

    // `dar_used` is published un-rounded.
    expectNumber(id, got['dar_used']! as double, want['dar_used']! as num,
        rounded: false);

    final gotStates = (got['states'] as List).cast<Map>();
    final wantStates = (want['states'] as List).cast<Map>();
    expect(gotStates, hasLength(wantStates.length),
        reason: '$id: states count');
    for (var j = 0; j < wantStates.length; j++) {
      final stateId = '$id.states[$j]';
      final gotState = gotStates[j].cast<String, Object?>();
      final wantState = wantStates[j].cast<String, Object?>();
      expect(gotState['id'], wantState['id'], reason: '$stateId: id');
      expect(gotState['state_after'], wantState['state_after'],
          reason: '$stateId: state_after');
      expectNumber(stateId, gotState['al']! as double, wantState['al']! as num,
          rounded: true);
    }

    for (final field in ['a', 'q']) {
      final gotValues = asMap(got[field]);
      final wantValues = asMap(want[field]);
      expectSameKeys('$id.$field', gotValues, wantValues);
      for (final entry in wantValues.entries) {
        expectNumber('$id.$field[${entry.key}]',
            (gotValues[entry.key]! as num).toDouble(), entry.value! as num,
            rounded: true);
      }
    }
  }

  /// The multi-round scenario generated from the real JS (see the file header).
  Map<String, Object?> multiRoundScenario() {
    final path = File('test/fixtures/mindnet_tierb_diagnosis.json');
    if (!path.existsSync()) {
      fail('missing ${path.path} - regenerate it with '
          '`node app/tool/gen_mindnet_tierb_diagnosis.cjs` (read-only on MindNet)');
    }
    final json = jsonDecode(path.readAsStringSync()) as Map<String, Object?>;
    return asMap(asMap(json['scenarios'])['multiround_progression']);
  }

  FastEngine buildEngine(Map<String, Object?> spec) {
    final ids = [for (final id in (spec['mechanisms'] as List)) id as String];
    final mechanisms = FastMechanisms.fromModuleDefaults(
      asMap(spec['module_defaults']),
      ids: ids,
      overrides: asMap(spec['overrides']),
    );
    final graph = FastGraph.fromSpec(
      asMap(spec['graph']),
      currentRealTime: (spec['hours'] as num?)?.toDouble() ?? 0,
    );
    // `config` carries things like `stable_rounds`; a scenario that relies on a
    // longer patience would otherwise stop as "cooling" early (B01 has no
    // `config` block, and the default is what it was generated with).
    final config = spec['config'] == null
        ? const FastConfig()
        : FastConfig.fromJson(asMap(spec['config']));
    return FastEngine(
      graph: graph,
      config: config,
      mechanisms: mechanisms,
      overrides: asMap(spec['overrides']),
      seed: (spec['seed'] as num?)?.toInt() ?? 11,
      hours: (spec['hours'] as num?)?.toDouble() ?? 0,
    )..startDiffusion(
        [for (final id in (spec['initial_nodes'] as List)) id as String],
        [for (final id in (spec['target_nodes'] as List)) id as String],
      );
  }

  group('B01 five-round diff', () {
    test('every published field of every round is reproduced', () {
      final engine = buildEngine(input);
      // Captured before any round, so "round 1 really evolved" can be asserted
      // against it instead of assumed.
      final initialStates = engine.finalStates();
      final initialActivation = {
        for (final id in engine.graph.nodeIds()) id: engine.activationOf(id),
      };
      final rounds = engine.runRounds(expected.length);

      expect(rounds, hasLength(5),
          reason: 'the vector is the generator\'s 5-step loop');

      for (var i = 0; i < rounds.length; i++) {
        compareRound('B01.rounds[$i]', rounds[i], expected[i]);
      }

      // Round 1 is a *real* round, and the stop is a judgement taken at its end -
      // not "the loop was never written" (§ the file header on B01's limits).
      expect(initialStates, {'A': 'CONSCIOUS', 'B': 'INACTIVE', 'C': 'INACTIVE'});
      expect(initialActivation, {'A': 1.0, 'B': 0.0, 'C': 0.0});
      expect(rounds.first.driveEdges, isNotEmpty,
          reason: 'round 1 produced edge contributions');
      expect(rounds.first.a['B']!, greaterThan(0.3),
          reason: 'B left its initial activation of 0');
      expect(engine.activationOf('B'), greaterThan(0.3));
      expect(engine.finalStates()['B'], 'CONSCIOUS',
          reason: 'B changed state in round 1');
      expect(engine.finalStates()['C'], 'SUBCONSCIOUS');
      // "Reached" is decided by `_everActivated`, and C only ever got as far as
      // SUBCONSCIOUS - so what stopped the run is the judgement, not
      // consciousness.
      expect(engine.everActivated, contains('C'));
      expect(engine.firstActivation['C'], 1);
      expect(engine.targetSteps, {'C': 1});

      // The post-round state is what a caller would read next.
      expect(engine.rounds, 1,
          reason: 'the target was activated in round 1, so the JS stops there');
      expect(engine.stopped, isTrue);
      expect(engine.stopReason, FastStop.allTargetsReached);
      expect(engine.targetsAllReached, isTrue);
      expect(engine.finalStates(),
          {'A': 'CONSCIOUS', 'B': 'CONSCIOUS', 'C': 'SUBCONSCIOUS'});
    });
  });

  group('multi-round progression (the goal does not light in round 1)', () {
    // B01 cannot tell "stopped correctly" from "never advanced" (see the header).
    // This scenario, generated from the real JS by the same read-only script, can:
    // the goal sits at the end of a long weak chain, round 1 leaves it dark, and
    // the engine genuinely executes six rounds before `_all_targets_active()`
    // ends the run.
    test('round increments, values evolve round over round, and the JS agrees',
        () {
      final scenario = multiRoundScenario();
      final spec = asMap(scenario['input']);
      final expected = asMap(scenario['expected']);
      final wantRounds =
          (expected['rounds'] as List).cast<Map<String, Object?>>();
      final wantRun = asMap(expected['run']);

      final engine = buildEngine(spec);
      expect(expected['target_lit_in_round_1'], isFalse,
          reason: 'the scenario is only useful if round 1 is dark for the goal');
      expect(engine.everActivated, isNot(contains('t')));

      final rounds = engine.runRounds(wantRounds.length);
      expect(rounds, hasLength(6));

      // 1) The same field-by-field comparison B01 gets - on six *distinct*
      //    rounds, every one of them produced by a real pipeline pass.
      for (var i = 0; i < rounds.length; i += 1) {
        compareRound('multiround.rounds[$i]', rounds[i], wantRounds[i]);
      }

      // 2) `round` increments: the property B01's five identical tuples hide.
      expect([for (final snapshot in rounds) snapshot.round], [1, 2, 3, 4, 5, 6]);
      expect(expected['round_numbers'], [1, 2, 3, 4, 5, 6]);

      // 3) No round is a repeat of the one before it.
      for (var i = 1; i < rounds.length; i += 1) {
        expect(rounds[i].toJson(), isNot(rounds[i - 1].toJson()),
            reason: 'round ${i + 1} must not be a copy of round $i');
      }

      // 4) The values move in the direction the mechanism predicts: the chain
      //    warms up hop by hop, and the far goal ramps towards `st` every round.
      for (var i = 1; i < rounds.length; i += 1) {
        expect(rounds[i].a['t']!, greaterThan(rounds[i - 1].a['t']!),
            reason: 'the far goal accumulates activation every round');
        expect(rounds[i].scores['n4']!, greaterThan(rounds[0].scores['n4']!),
            reason: 'n4 is above where it started');
      }
      expect(rounds[0].states.firstWhere((s) => s.id == 'n1').stateAfter,
          FastNodeState.subconscious);
      expect(rounds[0].states.firstWhere((s) => s.id == 'n2').stateAfter,
          FastNodeState.inactive);
      expect(rounds[1].states.firstWhere((s) => s.id == 'n1').stateAfter,
          FastNodeState.conscious,
          reason: 'n1 crossed ct in round 2: the chain advanced');
      expect(rounds[1].states.firstWhere((s) => s.id == 'n2').stateAfter,
          FastNodeState.subconscious,
          reason: 'n2 started receiving n1 in round 2');
      expect(rounds[4].states.firstWhere((s) => s.id == 'n4').stateAfter,
          FastNodeState.conscious);

      // 5) The goal stays dark until round 6 (`st = 0.05`), and *then* the stop is
      //    a judgement: `_all_targets_active()` sees it in `_everActivated`.
      for (var i = 0; i < rounds.length - 1; i += 1) {
        expect(rounds[i].a['t']!, lessThan(0.05),
            reason: 'round ${i + 1} must not have lit the goal');
        expect(rounds[i].states.firstWhere((s) => s.id == 't').stateAfter,
            FastNodeState.inactive);
      }
      expect(rounds.last.a['t']!, greaterThanOrEqualTo(0.05));
      expect(rounds.last.states.firstWhere((s) => s.id == 't').stateAfter,
          FastNodeState.subconscious);

      // 6) The run summary the generator recorded.
      expect(engine.rounds, wantRun['rounds_run']);
      expect(engine.stopped, wantRun['stopped']);
      expect(engine.stopReason, wantRun['stop_reason']);
      expect(engine.rounds, 6);
      expect(engine.stopReason, FastStop.allTargetsReached);
      expect(engine.targetsAllReached, isTrue);
      expect(engine.firstActivation['t'], 6);
      expect(engine.finalStates(), asMap(wantRun['final_states']));
      expect(engine.targetStepsOf().keys.toList(), ['t']);
      expect(engine.targetStepsOf(), asMap(wantRun['target_steps']));
      expect(engine.reachability(),
          closeTo((wantRun['reachability']! as num).toDouble(), 1e-12));
    });
  });

  group('pipeline semantics the diff alone could not catch', () {
    late FastEngine engine;

    setUp(() {
      engine = buildEngine(input);
    });

    test('activation uses the exact integral, not an explicit Euler step', () {
      // da/dt = alpha*x*(1-a) - lambda*a has the closed form
      //   a1 = a* + (a - a*)*exp(-k),  k = alpha*x + lambda,  a* = alpha*x/k
      // With a strong drive the Euler step would leave [0,1] immediately
      // (a + alpha*x*(1-a) - lambda*a = 50 at a = 0), while the exact integral
      // converges monotonically.
      const alpha = 0.5;
      const lambda = 0.2;
      const x = 100.0;
      final r = FastEngine.shuntingActivation(
        a: 0,
        q: 0,
        drive: x,
        theta: 0.05,
        alpha: alpha,
        lambda: lambda,
        etaQ: 0.5,
        lambdaQ: 0.3,
      );
      const k = alpha * x + lambda;
      const aStar = alpha * x / k;
      expect(r.k, closeTo(k, 1e-12));
      expect(r.aStar, closeTo(aStar, 1e-12));
      expect(r.a, closeTo(aStar + (0 - aStar) * math.exp(-k), 1e-15 * aStar));
      expect(r.a, lessThan(1.0),
          reason: 'the exact integral converges towards 0.996, not to 1');

      // Monotone convergence, the property MindNet's acceptance check asserts.
      var a = 0.0;
      var q = 0.0;
      var previous = -1.0;
      for (var i = 0; i < 50; i++) {
        final step = FastEngine.shuntingActivation(
          a: a,
          q: q,
          drive: x,
          theta: 0.05,
          alpha: alpha,
          lambda: lambda,
          etaQ: 0.5,
          lambdaQ: 0.3,
        );
        expect(step.a, greaterThanOrEqualTo(previous - 1e-12),
            reason: 'activation must not oscillate');
        previous = step.a;
        a = step.a;
        q = step.q;
      }
      expect(a, greaterThan(0.99));
      expect(a, lessThanOrEqualTo(1.0));

      // Decay without input is monotone downwards.
      a = 1;
      previous = a;
      for (var i = 0; i < 5; i++) {
        a = FastEngine.shuntingActivation(
          a: a,
          q: 0,
          drive: 0,
          theta: 0.05,
          alpha: alpha,
          lambda: lambda,
          etaQ: 0.5,
          lambdaQ: 0.3,
        ).a;
        expect(a, lessThan(previous));
        previous = a;
      }
      expect(a, lessThan(0.5));
    });

    test('start nodes are pinned back to a = 1 every round', () {
      final snapshot = engine.runRounds(1).single;
      expect(snapshot.a['A'], 1.0);
      expect(engine.activationOf('A'), 1.0);
      expect(snapshot.conscious, contains('A'));
      // A's own activation update ran first (it had drive 0.15), so this is
      // the pin and not "it never moved".
      expect(
        FastEngine.shuntingActivation(
          a: 1,
          q: 0,
          drive: 0.15,
          theta: 0.05,
          alpha: 0.5,
          lambda: 0.2,
          etaQ: 0.5,
          lambdaQ: 0.3,
        ).a,
        lessThan(1.0),
      );
    });

    test('capacity admits by activation budget, and the focus holds one item',
        () {
      final five = [
        for (var i = 0; i < 5; i++)
          (id: 'L$i', score: 1.0, a: 1.0),
      ];
      final strong = FastEngine.capacityAdmit(five, wDar: 4, wFa: 1);
      expect(strong.dar, hasLength(4),
          reason: 'W_DAR = 4 activation units, not "4 items regardless"');
      expect(strong.fa, hasLength(1), reason: 'W_FA = 1: the narrow focus');
      expect(strong.used, closeTo(4.0, 1e-15));

      // Weak candidates are cheaper, so strictly more of them fit: the budget
      // is in activation units (the contract's §6.4 warning about W_DAR).
      final weak = [
        for (var i = 0; i < 10; i++)
          (id: 'w$i', score: 0.5, a: 0.5),
      ];
      final weakAdmitted = FastEngine.capacityAdmit(weak, wDar: 4, wFa: 1);
      expect(weakAdmitted.dar.length, greaterThan(strong.dar.length));

      // Ties are broken by id ascending, which is what makes `admitted`
      // reproducible.
      final tie = FastEngine.capacityAdmit(
        [
          (id: 'b', score: 1.0, a: 0.5),
          (id: 'a', score: 1.0, a: 0.5),
        ],
        wDar: 4,
        wFa: 1,
      );
      expect(tie.dar, ['a', 'b']);
    });

    test('ignition is the hard threshold when T_ign = 0 and a sigmoid above it',
        () {
      expect(FastEngine.ignitionProbability(0.3, 0.3, 0), 1);
      expect(FastEngine.ignitionProbability(0.299999, 0.3, 0), 0);
      expect(FastEngine.ignitionProbability(0.3, 0.3, 0.05), closeTo(0.5, 1e-12));
      expect(FastEngine.ignitionProbability(0.6, 0.3, 0.05),
          greaterThan(0.99));
      expect(FastEngine.ignitionProbability(0, 0.3, 0.05), lessThan(0.01));

      final snapshot = engine.runRounds(1).single;
      expect(snapshot.ignition, isNotEmpty);
      for (final record in snapshot.ignition) {
        expect(record.tIgn, 0,
            reason: 'the vector pins T_ign = 0 (no random source)');
        expect(record.draw, isNull,
            reason: 'a hard threshold consumes no randomness (§6.1)');
        expect(record.hit, record.p >= 1,
            reason: 'p is 0 or 1 and hit follows it');
        expect(snapshot.conscious.contains(record.node), record.hit,
            reason: 'hit is exactly "entered consciousness"');
      }
    });

    test('T_ign > 0 in the ambiguous range fails loudly instead of guessing',
        () {
      // The stochastic branch needs mulberry32, which this round deliberately
      // does not port. A silent substitute would be a different model, so the
      // port refuses to run it - and this test is what keeps that honest.
      final stochastic = FastEngine(
        graph: FastGraph.fromSpec(
          asMap(input['graph']),
          currentRealTime: 0,
        ),
        mechanisms: FastMechanisms.fromModuleDefaults(
          asMap(input['module_defaults']),
          ids: [for (final id in (input['mechanisms'] as List)) id as String],
          overrides: {'attention.ignition.T_ign': 0.05},
        ),
        overrides: {'attention.ignition.T_ign': 0.05},
      )..startDiffusion(['A'], ['C']);
      expect(
        () => stochastic.step(),
        throwsA(isA<UnsupportedError>().having(
          (e) => e.message,
          'message',
          contains('随机点火'),
        )),
      );
    });

    test('the target itself never takes the goal bias', () {
      final snapshot = engine.runRounds(1).single;
      final moduleEdges = [
        for (final edge in snapshot.driveEdges)
          if (edge.kind == 'module') edge.to,
      ];
      expect(moduleEdges, isNot(contains('C')),
          reason: 'otherwise the goal would light itself up in round 1');
      expect(moduleEdges, containsAll(<String>['A', 'B']));

      // A and B are one hop from C, so gamma = 0.5 and the lift is
      // beta_goal * 0.5 = 0.15; C keeps exactly its in-edge drive.
      expect(snapshot.drive['A'], closeTo(0.15, 1e-12));
      expect(snapshot.drive['B'], closeTo(0.72 + 0.15, 1e-12));
      expect(snapshot.drive['C'], closeTo(0.24, 1e-12));

      // And the distances are the directed ones (reverse BFS from the goal).
      final graph = FastGraph.fromSpec(asMap(input['graph']), currentRealTime: 0);
      expect(FastEngine.distanceToGoals(graph, ['C']), {'C': 0, 'B': 1, 'A': 1});
      expect(FastEngine.goalRelevance(null, 0.5), 0,
          reason: 'unreachable nodes get no bias');
    });

    test('no rhythm.gate means availability is exactly 1 every round', () {
      final rounds = engine.runRounds(5);
      for (final snapshot in rounds) {
        expect(snapshot.availability, 1.0);
        expect(snapshot.cycleTicks, 1);
      }
      // Only round 1 actually ran (the diffusion stopped at the end of it), so
      // exactly one tick was consumed.
      expect(engine.rounds, 1);
      expect(engine.tick, 1, reason: 'one tick per executed round, cycle = 1');
    });

    test('a stopped engine repeats its last round (the fixture\'s 5 snapshots)',
        () {
      final rounds = engine.runRounds(5);
      final first = rounds.first.toJson();
      for (var i = 1; i < rounds.length; i++) {
        expect(rounds[i].round, 1,
            reason: 'the JS reads _lastRound, which a stopped step does not '
                'touch');
        expect(rounds[i].toJson(), first);
      }

      // The no-op is a real no-op: a stopped step counts no round, consumes no
      // tick, does not rebuild the snapshot object, and leaves the live fast
      // state alone. (Asserted separately from the JSON diff above, because
      // "same values" could in principle also come from a rebuild.)
      final lastRound = engine.lastRound;
      final activation = {
        for (final id in engine.graph.nodeIds()) id: engine.activationOf(id),
      };
      final subthreshold = {
        for (final id in engine.graph.nodeIds()) id: engine.subthresholdOf(id),
      };
      final roundsBefore = engine.rounds;
      final status = engine.step();
      expect(engine.rounds, roundsBefore, reason: 'no round is counted');
      expect(status.round, roundsBefore,
          reason: 'the JS reports the unchanged counter on a no-op step');
      expect(identical(engine.lastRound, lastRound), isTrue,
          reason: 'the last round must not be rebuilt');
      expect(engine.lastRound!.admitted, first['admitted']);
      expect(engine.lastRound!.darUsed, first['dar_used']);
      expect(engine.tick, 1, reason: 'no tick is consumed either');
      for (final id in engine.graph.nodeIds()) {
        expect(engine.activationOf(id), activation[id]);
        expect(engine.subthresholdOf(id), subthreshold[id]);
      }
    });

    test('the identical rounds are a stop, not a static model', () {
      // B01's five tuples are identical because the run **stopped after round
      // 1**, so a diff over them cannot by itself detect "the state machine no
      // longer advances". This test drives the same graph with no target: there
      // is nothing to "reach", the run keeps going, and the rounds visibly
      // differ - which is what proves the pipeline advances when it is allowed
      // to.
      final spec = Map<String, Object?>.of(input)..['target_nodes'] = <String>[];
      final running = buildEngine(spec);
      final snapshots = running.runRounds(2);

      expect(running.stopped, isFalse,
          reason: 'with no target nothing can be "reached"');
      expect(running.rounds, 2, reason: 'both rounds really ran');
      expect(snapshots[1].toJson(), isNot(snapshots[0].toJson()));
      expect(snapshots[1].scores['C']!, greaterThan(snapshots[0].scores['C']!),
          reason: 'C keeps accumulating activation');
      expect(snapshots[1].drive['C']!, greaterThan(snapshots[0].drive['C']!),
          reason: "round 2's drive for C includes B's activation: the state "
              'machine moved');
      expect(snapshots[1].driveEdges.any((e) => e.from == 'B' && e.to == 'C'),
          isTrue,
          reason: 'B → C is a second-round contribution that round 1 cannot have');
    });

    test('the target counts as "reached" once it was merely sub-conscious', () {
      // C never entered consciousness in B01 (score 0.1027 < ct 0.3), yet
      // targets_all_reached is true: MindNet's `_all_targets_active` asks
      // `everActivated`, which includes SUBCONSCIOUS. Pinned because a
      // "tidied up" port would silently require CONSCIOUS here.
      final snapshot = engine.runRounds(1).single;
      expect(snapshot.states.firstWhere((s) => s.id == 'C').stateAfter,
          FastNodeState.subconscious);
      expect(engine.targetsAllReached, isTrue);
      expect(engine.targetSteps, {'C': 1});
    });
  });

  group('the projection bridge', () {
    test('a CognitiveGraph projects straight into the fast layer', () {
      // The whole adapter, and the reason this port does not carry a second
      // graph model: `cognitive_graph.dart` already emits MindNet's input
      // shape, `FastGraph.fromSpec` reads it.
      final projected = FastGraph.fromSpec(
        const CognitiveGraph(
          nodes: [
            CognitiveNode(id: 'p', name: '父', ms: 0.8),
            CognitiveNode(id: 'c1', name: '子一', ms: 0.7),
            CognitiveNode(id: 'c2', name: '子二', ms: 0.6),
          ],
          edges: [
            CognitiveEdge(id: 'pc:p->c1', from: 'p', to: 'c1', ls: 0.7),
            CognitiveEdge(id: 'pc:p->c2', from: 'p', to: 'c2', ls: 0.7),
            CognitiveEdge(id: 'sib:c1->c2', from: 'c1', to: 'c2', ls: 0.4),
          ],
        ).toJson(),
        currentRealTime: 200,
      );
      expect(projected.nodeIds(), ['p', 'c1', 'c2']);
      expect(projected.getNode('p')!.lastReviewTime, 200,
          reason: 'last_review_time 0/missing is fixed at load (§3.1)');
      expect(projected.getNode('p')!.ms, 0.8);

      final engine = FastEngine(
        graph: projected,
        mechanisms: FastMechanisms.fromModuleDefaults(
          asMap(input['module_defaults']),
          ids: const [
            FastMechanisms.shunting,
            FastMechanisms.capacity,
            FastMechanisms.ignition,
            FastMechanisms.goal,
          ],
          overrides: const {'attention.ignition.T_ign': 0},
        ),
        overrides: const {'attention.ignition.T_ign': 0},
      )..startDiffusion(const ['p'], const ['c2']);
      final snapshot = engine.runRounds(1).single;
      expect(snapshot.a['p'], 1.0);
      expect(snapshot.states.firstWhere((s) => s.id == 'c1').stateAfter,
          FastNodeState.subconscious,
          reason: 'drive 0.71 lands at a = 0.272, below ct = 0.3');
      expect(snapshot.drive['c1'], closeTo(0.56 + 0.15, 1e-12));
      expect(snapshot.drive['c2'], closeTo(0.56, 1e-12),
          reason: 'the target takes no bias, even when it is also a cue');
      expect(engine.stopped, isTrue,
          reason: 'c2 reached subconscious, which counts as "activated"');
      expect(engine.stopReason, FastStop.allTargetsReached);
    });
  });

  group('source-level guarantees', () {
    test('the port contains no dart:math randomness', () {
      // D3 / §6.1: no random source is ported this round, so nothing here may
      // call Random - not even "just for a tie-break".
      for (final path in [
        'lib/domain/services/cognitive/fast_engine.dart',
        'lib/domain/services/cognitive/fast_diagnosis.dart',
      ]) {
        final source = File(path).readAsStringSync();
        expect(source.contains('Random'), isFalse,
            reason: '$path must not pull in a random source');
      }
    });
  });
}
