/// Pure Dart port of MindNet's control layer: the bottleneck diagnosis
/// (`mechanisms/diagnosis.bottleneck.js`) and the counterfactual planner
/// (`mechanisms/control.planner.js`).
///
/// Provenance: the read-only MindNet checkout at `f4eec9b`. Unlike the fast
/// layer, **these two modules have no published conformance vectors** — the
/// agreed snapshot (`test/fixtures/mindnet_vectors.json`) only covers the round
/// pipeline. So the expectations for this file live in
/// `test/fixtures/mindnet_tierb_diagnosis.json`, generated by
/// `app/tool/gen_mindnet_tierb_diagnosis.cjs`, which `require`s the real JS
/// modules and records their output. That generator never writes to MindNet
/// (see its header).
///
/// ## Why the diagnosis is the useful half for Furnace
///
/// `docs/MINDNET_CONTRACT.md` §6.3 recommends this exact shape for "is this
/// knowledge point in the development zone or a dead corner?":
/// `empty` (no cue can reach it / the cue is too faint) means a dead corner,
/// `weak` (it almost came back) means the development zone, and `overload`
/// means the student *can* do it but too much was competing at once — a
/// distinction no FSRS-style scheduler can express. The planner adds "what
/// would it buy?", priced by re-running a **clone** of the engine.
///
/// ## Two seams that are explicit rather than hidden
///
/// * **`danger` is not computed here.** MindNet's danger zone is published by
///   `metacognition.belief` (confidence high, retrievability low), which is not
///   part of the tierB port. So [FastDiagnosis.bottlenecks] takes the rows as an
///   argument and folds them in exactly the way the JS hook does, and nothing
///   pretends the confidence model ran.
/// * **Retention interventions need the memory layer.** `strengthen_impression`
///   / `interval_retrieval` / `lower_threshold` are priced by how much retention
///   they buy, which is tierA's `R = R0·Ψ(t/S)`. [FastPlanner.plan] takes a
///   [RetentionProbe]; when none is supplied it reports those entries as
///   un-simulated with the JS's own wording for "memory module not loaded".
library;

import 'dart:math' as math;

import 'fast_engine.dart';

/// `diagnosis.bottleneck`'s three parameters.
///
/// All three are **未标定 / NOT CALIBRATED** on the reference side; the values
/// are read from [FastDiagnosisParams.fromJson] (the fixture carries MindNet's
/// `DEFAULTS`) rather than repeated at call sites (§6.6).
class FastDiagnosisParams {
  const FastDiagnosisParams({
    this.closenessWeak = 0.6,
    this.slowRounds = 3,
    this.severityWeight = 1.0,
  });

  factory FastDiagnosisParams.fromJson(Map<String, Object?> json) =>
      FastDiagnosisParams(
        closenessWeak: (json['closeness_weak'] as num?)?.toDouble() ?? 0.6,
        slowRounds: (json['slow_rounds'] as num?)?.toInt() ?? 3,
        severityWeight: (json['severity_weight'] as num?)?.toDouble() ?? 1.0,
      );

  /// The lower bound for "almost had it": peak drive as a share of `ct`.
  final double closenessWeak;

  /// A target that only lit up after this many rounds counts as "slow".
  final int slowRounds;

  /// Weight of node importance inside severity.
  final double severityWeight;
}

/// The seven bottleneck types.
///
/// The JS treats them as strings; an enum keeps the set closed (the contract
/// warns the set may *grow*, which would be a deliberate port change, not a
/// silent one).
enum BottleneckType {
  empty('empty', '空（没有候选 / 缺入口）'),
  weak('weak', '弱（差点想起来）'),
  slow('slow', '慢（频率不够）'),
  overload('overload', '超载（会，但被容量挤出去）'),
  offGoal('off_goal', '初筛错 / 跑偏（亮了但与目标无关）'),
  danger('danger', '危险区（自信高、实际想不起来）'),
  deadEnd('dead_end', '死路（没有出边，想到了也走不下去）');

  const BottleneckType(this.id, this.label);

  /// The wire value (`off_goal`, …); compared exactly against the vectors.
  final String id;

  /// The human label from the JS `TYPE_LABEL` table.
  final String label;

  static BottleneckType? fromId(String? id) {
    for (final type in values) {
      if (type.id == id) {
        return type;
      }
    }
    return null;
  }
}

/// Prescriptions: bottleneck → instruction ids (the instruction library lives in
/// [FastPlanner.instructions]).
const Map<BottleneckType, List<String>> kBottleneckPrescriptions = {
  BottleneckType.empty: [
    'add_in_edges',
    'add_connection_types',
    'lower_threshold',
    'support_subthreshold',
  ],
  BottleneckType.weak: [
    'lower_threshold',
    'strengthen_impression',
    'interval_retrieval',
  ],
  BottleneckType.slow: [
    'reduce_step_depth',
    'high_freq_light_task',
    'commit_temp_links',
  ],
  BottleneckType.overload: [
    'offload_working_memory',
    'chunk_problem',
    'capture_thought',
  ],
  BottleneckType.offGoal: ['correct_error', 'commit_temp_links', 'boost_clarity'],
  BottleneckType.danger: [
    'interval_retrieval',
    'boost_random_access',
    'strengthen_impression',
  ],
  BottleneckType.deadEnd: ['add_out_edges', 'add_relation_types'],
};

/// What `classify` decides, before the engine-level fields are attached.
class BottleneckVerdict {
  const BottleneckVerdict({
    required this.type,
    this.subtype,
    this.closeness,
    required this.note,
    this.also = const <String>[],
  });

  final BottleneckType type;

  /// `no_entry` / `too_faint`, or null.
  final String? subtype;

  final double? closeness;
  final String note;

  /// Other types that also apply (`slow` is the only one the JS emits today).
  final List<String> also;
}

/// One node's verdict as the control layer reports it.
class FastBottleneck {
  const FastBottleneck({
    required this.node,
    required this.name,
    required this.type,
    this.subtype,
    this.also = const <String>[],
    required this.label,
    this.closeness,
    required this.note,
    required this.severity,
    required this.prescriptions,
    required this.evidence,
    this.hasSubtypeKey = true,
    this.hasAlsoKey = true,
  });

  final String node;
  final String name;
  final BottleneckType type;
  final String? subtype;
  final List<String> also;
  final String label;
  final double? closeness;
  final String note;

  /// `weight * deficit * severity_weight`, rounded like the JS.
  final double severity;

  final List<String> prescriptions;
  final Map<String, Object?> evidence;

  /// The JS danger branch builds objects without `subtype`/`also` keys at all,
  /// so the difference is carried instead of being flattened into `null`.
  final bool hasSubtypeKey;
  final bool hasAlsoKey;

  Map<String, Object?> toJson() => {
        'node': node,
        'name': name,
        'type': type.id,
        if (hasSubtypeKey) 'subtype': subtype,
        if (hasAlsoKey) 'also': also,
        'label': label,
        'closeness': closeness,
        'note': note,
        'severity': severity,
        'prescriptions': prescriptions,
        'evidence': evidence,
      };
}

/// One metacognition row (`kernel.m.metacognition.danger[i]`).
class FastDangerRow {
  const FastDangerRow({
    required this.node,
    required this.name,
    required this.belief,
    required this.r,
    required this.diff,
  });

  factory FastDangerRow.fromJson(Map<String, Object?> json) => FastDangerRow(
        node: json['node']! as String,
        name: (json['name'] as String?) ?? json['node']! as String,
        belief: (json['belief'] as num?)?.toDouble() ?? 0,
        r: (json['R'] as num?)?.toDouble() ?? 0,
        diff: (json['diff'] as num?)?.toDouble() ?? 0,
      );

  final String node;
  final String name;

  /// Confidence the model thinks the student has (0..1).
  final double belief;

  /// Actual retrievability `R` at the same moment.
  final double r;

  /// `belief - R`.
  final double diff;
}

/// The bottleneck diagnosis.
abstract final class FastDiagnosis {
  /// The pure classifier, a line-for-line port of the JS `classify`.
  ///
  /// [reachesGoal] is the hook-level enrichment: whether the node can reach any
  /// target *at all*. It is deliberately a separate argument because the JS fact
  /// table does not carry it and because its `null` case (no targets were set)
  /// means "off-goal is not a meaningful verdict", not "false".
  static BottleneckVerdict? classify(
    FastDiagnosticFact fact,
    FastDiagnosisParams params, {
    bool? reachesGoal,
  }) {
    if (fact.isStart) {
      return null;
    }
    if (fact.outcompeted && fact.score >= fact.ct) {
      // Saying "cannot do it" here would be wrong: the knowledge is there, too
      // much came in at once. This is why the type exists at all.
      return const BottleneckVerdict(
        type: BottleneckType.overload,
        note: '进了候选但被容量挤出，不是知识缺口',
      );
    }
    if (fact.inDegree == 0) {
      return const BottleneckVerdict(
        type: BottleneckType.empty,
        subtype: 'no_entry',
        closeness: 0,
        note: '没有任何入边，线索再多也传不进来',
      );
    }
    final also = <String>[];
    if (fact.isTarget &&
        fact.firstActivationRound != null &&
        fact.firstActivationRound! > params.slowRounds) {
      also.add('slow');
    }
    // Everything that did not enter consciousness: never lit / only
    // sub-conscious / lit and fell back again.
    if (fact.state != FastNodeState.conscious) {
      final strength = math.max(fact.score, fact.peakDrive);
      final closeness = fact.ct > 0 ? strength / fact.ct : 0.0;
      if (closeness >= params.closenessWeak) {
        return BottleneckVerdict(
          type: BottleneckType.weak,
          closeness: closeness,
          also: also,
          note: '已到阈值的 ${_percent(closeness)}%'
              '${fact.everActivated ? '（曾点亮、已回落）' : ''}，但没过线',
        );
      }
      return BottleneckVerdict(
        type: BottleneckType.empty,
        subtype: 'too_faint',
        closeness: closeness,
        also: also,
        note: '线索太弱：峰值只有阈值的 ${_percent(closeness)}%'
            '${fact.everActivated ? '（曾点亮）' : ''}',
      );
    }
    if (also.contains('slow')) {
      return BottleneckVerdict(
        type: BottleneckType.slow,
        note: '第 ${fact.firstActivationRound} 轮才亮',
      );
    }
    if (!fact.isTarget && reachesGoal == false) {
      return const BottleneckVerdict(
        type: BottleneckType.offGoal,
        note: '亮了，但走不到任何目标（跑偏分支）',
      );
    }
    if (fact.outDegree == 0 && !fact.isTarget) {
      return const BottleneckVerdict(
        type: BottleneckType.deadEnd,
        note: '没有出边',
      );
    }
    return null;
  }

  /// Reverse reachability: which nodes can walk to a target along out-edges.
  static Map<String, bool> reachableToTargets(FastGraph graph, List<String> targets) {
    final ok = <String, bool>{};
    final queue = <String>[];
    for (final target in targets) {
      if (!graph.hasNode(target)) {
        continue;
      }
      ok[target] = true;
      queue.add(target);
    }
    for (var head = 0; head < queue.length; head += 1) {
      for (final edge in graph.inEdges(queue[head])) {
        if (ok[edge.from] == true) {
          continue;
        }
        ok[edge.from] = true;
        queue.add(edge.from);
      }
    }
    return ok;
  }

  /// The engine-level hook: facts → bottlenecks, sorted by severity.
  ///
  /// [dangerRows] are the metacognition rows, folded in exactly as the JS hook
  /// does (including the "do not duplicate an existing danger row" guard).
  static List<FastBottleneck> bottlenecks({
    required FastEngine engine,
    FastDiagnosisParams params = const FastDiagnosisParams(),
    List<FastDangerRow> dangerRows = const <FastDangerRow>[],
  }) {
    final facts = engine.diagnosticFacts();
    final targets = engine.targets;
    final reach = reachableToTargets(engine.graph, targets);
    final hasTargets = targets.isNotEmpty;
    final out = <FastBottleneck>[];

    for (final node in engine.graph.nodes.values) {
      final fact = facts[node.id]!;
      final verdict = classify(
        fact,
        params,
        reachesGoal: hasTargets ? reach[node.id] == true : null,
      );
      if (verdict == null) {
        continue;
      }
      final deficit = verdict.type == BottleneckType.overload
          ? 0.5
          : math.max(0.05, 1 - (verdict.closeness ?? 0.5));
      out.add(FastBottleneck(
        node: node.id,
        name: node.name,
        type: verdict.type,
        subtype: verdict.subtype,
        also: verdict.also,
        label: verdict.type.label +
            (verdict.subtype == 'too_faint'
                ? '（线索太弱）'
                : verdict.subtype == 'no_entry'
                    ? '（没有入口）'
                    : ''),
        closeness: verdict.closeness,
        note: verdict.note,
        severity: FastEngine.round6(
            node.weight * deficit * params.severityWeight),
        prescriptions:
            List<String>.of(kBottleneckPrescriptions[verdict.type]!),
        evidence: {
          'state': fact.state.id,
          'peak_drive': fact.peakDrive,
          'ct': fact.ct,
          'st': fact.st,
          'in_degree': fact.inDegree,
          'out_degree': fact.outDegree,
          'outcompeted': fact.outcompeted,
          'weight': node.weight,
        },
      ));
    }

    for (final row in dangerRows) {
      final node = engine.graph.getNode(row.node);
      if (node == null) {
        continue;
      }
      if (out.any((b) =>
          b.node == row.node && b.type == BottleneckType.danger)) {
        continue;
      }
      out.add(FastBottleneck(
        node: row.node,
        name: row.name,
        type: BottleneckType.danger,
        label: BottleneckType.danger.label,
        note: '自信 ${jsNumber(row.belief)} 而实际可提取度只有 ${jsNumber(row.r)}',
        severity: FastEngine.round6(
            node.weight * math.max(0.05, row.diff) * params.severityWeight),
        prescriptions: List<String>.of(kBottleneckPrescriptions[BottleneckType.danger]!),
        evidence: {'belief': row.belief, 'R': row.r, 'diff': row.diff},
        hasSubtypeKey: false,
        hasAlsoKey: false,
      ));
    }

    // Severity descending. The sort must be **stable**: JS `Array.prototype.sort`
    // is stable by spec, and ties do happen (equal severity across nodes), so an
    // unstable Dart sort would reorder them and break the diff.
    stableSortBy(out, (b) => -b.severity);
    return out;
  }

  static String _percent(double closeness) =>
      (closeness * 100).toStringAsFixed(0);
}

/// One entry of the instruction library (`INSTRUCTIONS` in `control.planner.js`).
class FastInstruction {
  const FastInstruction({
    required this.id,
    required this.name,
    required this.source,
    required this.simulatable,
  });

  final String id;
  final String name;

  /// `application` (the 17-instruction library) or `executive`.
  final String source;

  /// Whether this engine can express the intervention at all. Those that cannot
  /// are reported as rules only - never as "predicted 0 gain".
  final bool simulatable;
}

/// The counterfactual planner's parameters (all **未标定** on the reference side).
class FastPlannerParams {
  const FastPlannerParams({
    this.simRounds = 4,
    this.retentionHorizonHours = 24,
    this.maxCandidates = 4,
    this.costRetrieval = 1.0,
    this.costLink = 2.0,
    this.costOffload = 0.2,
  });

  factory FastPlannerParams.fromJson(Map<String, Object?> json) =>
      FastPlannerParams(
        simRounds: (json['sim_rounds'] as num?)?.toInt() ?? 4,
        retentionHorizonHours:
            (json['retention_horizon_hours'] as num?)?.toDouble() ?? 24,
        maxCandidates: (json['max_candidates'] as num?)?.toInt() ?? 4,
        costRetrieval: (json['cost_retrieval'] as num?)?.toDouble() ?? 1.0,
        costLink: (json['cost_link'] as num?)?.toDouble() ?? 2.0,
        costOffload: (json['cost_offload'] as num?)?.toDouble() ?? 0.2,
      );

  /// How many rounds a topology/capacity intervention is simulated forward.
  final int simRounds;

  /// The horizon at which a retrieval intervention's retention is compared.
  final double retentionHorizonHours;

  /// Only the top N bottlenecks are planned (compute budget).
  final int maxCandidates;

  final double costRetrieval;
  final double costLink;
  final double costOffload;
}

/// What applying one intervention to a cloned engine did.
class FastInterventionOutcome {
  const FastInterventionOutcome({
    required this.applied,
    required this.cost,
    this.metric,
    required this.why,
  });

  final bool applied;
  final double cost;

  /// `reachability` / `retention`, or null when nothing was simulated.
  final String? metric;

  final String why;
}

/// One line of the plan: a bottleneck, an instruction, and what it would buy.
class FastPlanEntry {
  FastPlanEntry({
    required this.node,
    required this.name,
    required this.bottleneck,
    required this.instruction,
    required this.instructionName,
    required this.source,
  });

  final String node;
  final String name;
  final BottleneckType bottleneck;
  final String instruction;
  final String instructionName;
  final String source;

  /// False means "rule mapping only": either the engine cannot express the
  /// intervention, or it was not simulated this round. It never means "this was
  /// priced at zero".
  bool simulated = false;

  double gain = 0;
  double cost = 0;
  double value = 0;
  String why = '';
  String? metric;

  Map<String, Object?> toJson() => {
        'node': node,
        'name': name,
        'bottleneck': bottleneck.id,
        'instruction': instruction,
        'instruction_name': instructionName,
        'source': source,
        'simulated': simulated,
        'gain': gain,
        'cost': cost,
        'value': value,
        'why': why,
        if (metric != null) 'metric': metric,
      };
}

/// Prices a retention-metric intervention: `R` at [u] for [nodeId].
///
/// Supplied by the caller because retention is tierA's math
/// (`memoryDsr.retrievabilityOf`, ported as `DsrMemory`), not the fast layer's.
/// Returning null means "cannot be computed", which the planner reports with the
/// JS's own wording rather than as a zero gain.
typedef RetentionProbe = double? Function(
  FastEngine engine,
  String nodeId,
  double u,
);

/// The planner: diagnosis → instruction → counterfactual prediction.
abstract final class FastPlanner {
  /// The instruction library: 17 from MindNet's Application_Protocol plus the
  /// executive-layer ones. `simulatable` is the honesty switch.
  static const Map<String, FastInstruction> instructions = {
    'set_context': FastInstruction(
        id: 'set_context',
        name: '设定上下文（写一句"我现在要解决的是____"）',
        source: 'application',
        simulatable: false),
    'capture_thought': FastInstruction(
        id: 'capture_thought',
        name: '捕捉念头（不判断地记一句）',
        source: 'application',
        simulatable: false),
    'lower_threshold': FastInstruction(
        id: 'lower_threshold',
        name: '降低门槛（用弱线索反复试探）',
        source: 'application',
        simulatable: true),
    'boost_random_access': FastInstruction(
        id: 'boost_random_access',
        name: '提升随机访问（换 3 个入口抽问）',
        source: 'application',
        simulatable: false),
    'boost_clarity': FastInstruction(
        id: 'boost_clarity',
        name: '提升清晰度（回忆后强制列细节）',
        source: 'application',
        simulatable: false),
    'selective_automation': FastInstruction(
        id: 'selective_automation',
        name: '选择性自动化（重复到不看步骤，并核对）',
        source: 'application',
        simulatable: false),
    'staged_processing': FastInstruction(
        id: 'staged_processing',
        name: '分阶段处理（先套旧框架，再换角度重组）',
        source: 'application',
        simulatable: false),
    'add_connection_types': FastInstruction(
        id: 'add_connection_types',
        name: '增加连接类型（结构/情境/行动/自我 四问）',
        source: 'application',
        simulatable: false),
    'add_out_edges': FastInstruction(
        id: 'add_out_edges',
        name: '增加出边（它能联想到什么、能做什么）',
        source: 'application',
        simulatable: false),
    'add_in_edges': FastInstruction(
        id: 'add_in_edges',
        name: '增加入边（"当出现____时，我该想到____"）',
        source: 'application',
        simulatable: true),
    'add_relation_types': FastInstruction(
        id: 'add_relation_types',
        name: '增加关系类型（给 A、B 标 ≥2 种关系）',
        source: 'application',
        simulatable: false),
    'correct_error': FastInstruction(
        id: 'correct_error',
        name: '更正错误（保留错误联想，标"此路不通"）',
        source: 'application',
        simulatable: false),
    'commit_temp_links': FastInstruction(
        id: 'commit_temp_links',
        name: '提交临时连接（线索→知识→操作→边界）',
        source: 'application',
        simulatable: false),
    'toggle_mode': FastInstruction(
        id: 'toggle_mode',
        name: '切换思维模式（发散 2 分钟 / 收敛筛选）',
        source: 'application',
        simulatable: false),
    'interval_retrieval': FastInstruction(
        id: 'interval_retrieval',
        name: '间隔提取（等到间隔到了再主动提取）',
        source: 'application',
        simulatable: true),
    'strengthen_impression': FastInstruction(
        id: 'strengthen_impression',
        name: '增强印象（合上材料主动回忆，写不出再看一眼再重写）',
        source: 'application',
        simulatable: true),
    'support_subthreshold': FastInstruction(
        id: 'support_subthreshold',
        name: '支持亚阈积累（只记录、不评价、定期回看）',
        source: 'application',
        simulatable: false),
    'offload_working_memory': FastInstruction(
        id: 'offload_working_memory',
        name: '写下来释放工作记忆',
        source: 'executive',
        simulatable: true),
    'reduce_step_depth': FastInstruction(
        id: 'reduce_step_depth',
        name: '降单步深度（把一步拆成更小的子步）',
        source: 'executive',
        simulatable: false),
    'chunk_problem': FastInstruction(
        id: 'chunk_problem',
        name: '把大问题切成小块',
        source: 'executive',
        simulatable: false),
    'high_freq_light_task': FastInstruction(
        id: 'high_freq_light_task',
        name: '先退到高频轻任务，把节奏拉起来',
        source: 'executive',
        simulatable: false),
  };

  /// Bottleneck → preferred instruction (the rest are output as alternatives).
  static const Map<BottleneckType, String> primary = {
    BottleneckType.empty: 'add_in_edges',
    BottleneckType.weak: 'strengthen_impression',
    BottleneckType.slow: 'reduce_step_depth',
    BottleneckType.overload: 'offload_working_memory',
    BottleneckType.offGoal: 'correct_error',
    BottleneckType.danger: 'interval_retrieval',
    BottleneckType.deadEnd: 'add_out_edges',
  };

  /// Applies one intervention to an engine (in practice: to a clone).
  static FastInterventionOutcome applyIntervention(
    FastEngine engine,
    String nodeId,
    String instruction,
    FastPlannerParams params,
  ) {
    switch (instruction) {
      case 'strengthen_impression':
        engine.review(nodeId, {
          'type': 'retrieval_success',
          'grade': 3,
        });
        return FastInterventionOutcome(
          applied: true,
          cost: params.costRetrieval,
          metric: 'retention',
          why: '一次主动提取成功（提高稳定度 S 与编码强度 R0）',
        );
      case 'interval_retrieval':
        engine.review(nodeId, {
          'type': 'retrieval_success',
          'grade': 2,
        });
        return FastInterventionOutcome(
          applied: true,
          cost: params.costRetrieval,
          metric: 'retention',
          why: '间隔后的主动提取（更费力，增益结构不同）',
        );
      case 'lower_threshold':
        engine.review(nodeId, {
          'type': 'retrieval_failure_feedback',
          'grade': 2,
          'closeness': 0.85,
        });
        return FastInterventionOutcome(
          applied: true,
          cost: params.costRetrieval,
          metric: 'retention',
          why: '弱线索试探 + 对答案（合意难度）',
        );
      case 'add_in_edges':
        // The clue most likely to be thought of, that is not connected yet.
        String? best;
        var bestScore = 0.0;
        for (final node in engine.graph.nodes.values) {
          if (node.id == nodeId) {
            continue;
          }
          if (engine.graph.inEdges(nodeId).any((e) => e.from == node.id)) {
            continue;
          }
          final score = node.activation;
          if (score > bestScore) {
            bestScore = score;
            best = node.id;
          }
        }
        if (best == null || bestScore <= 0) {
          return const FastInterventionOutcome(
            applied: false,
            cost: 0,
            why: '没有可用的线索节点（当前没有别的节点被点亮）',
          );
        }
        engine.graph.addEdge(FastEdge(
          id: 'hypo_${best}_$nodeId',
          from: best,
          to: nodeId,
          ls: 0.8,
        ));
        return FastInterventionOutcome(
          applied: true,
          cost: params.costLink,
          metric: 'reachability',
          why: '补一条入边：$best → $nodeId',
        );
      case 'offload_working_memory':
        const key = 'attention.capacity.W_DAR';
        final current = engine.numberParam(key, 4);
        // Written to the *engine passed in* - the JS kernel's override map is
        // per-kernel for exactly this reason (a clone's override must not leak
        // back into the original).
        engine.overrides[key] = current * 1.5;
        return FastInterventionOutcome(
          applied: true,
          cost: params.costOffload,
          metric: 'reachability',
          why: '把直接访问区容量从 ${jsNumber(current)} 临时放宽到 '
              '${(current * 1.5).toStringAsFixed(2)}',
        );
      default:
        return const FastInterventionOutcome(
          applied: false,
          cost: 0,
          why: '该指令改变的是执行层用法，本引擎没有对应状态，未做模拟',
        );
    }
  }

  /// Builds the plan: for the top bottlenecks, every candidate instruction, its
  /// counterfactual gain and its value.
  ///
  /// Note what `simulated: false` means in each case: for an instruction the
  /// engine cannot express it is "rule only", and for a retention instruction
  /// without a [RetentionProbe] it is "the memory layer is not wired". Neither is
  /// a zero.
  static List<FastPlanEntry> plan({
    required FastEngine engine,
    required List<FastBottleneck> bottlenecks,
    FastPlannerParams params = const FastPlannerParams(),
    RetentionProbe? retentionProbe,
  }) {
    final baselineReach = engine.reachability();
    final plan = <FastPlanEntry>[];
    final top = bottlenecks
        .take(math.max(1, params.maxCandidates.round()))
        .toList();

    for (final bottleneck in top) {
      final preferred = primary[bottleneck.type];
      final candidates = <String>[
        if (preferred != null) preferred,
        ...bottleneck.prescriptions.where((p) => p != preferred),
      ];
      final seen = <String>{};
      for (final instruction in candidates) {
        if (!seen.add(instruction)) {
          continue;
        }
        final meta = instructions[instruction] ??
            FastInstruction(
              id: instruction,
              name: instruction,
              source: 'unknown',
              simulatable: false,
            );
        final entry = FastPlanEntry(
          node: bottleneck.node,
          name: bottleneck.name,
          bottleneck: bottleneck.type,
          instruction: instruction,
          instructionName: meta.name,
          source: meta.source,
        );
        if (meta.simulatable && params.simRounds > 0) {
          try {
            final clone = engine.clone();
            final outcome =
                applyIntervention(clone, bottleneck.node, instruction, params);
            if (outcome.applied) {
              entry.simulated = true;
              entry.cost = outcome.cost;
              final horizon = params.retentionHorizonHours;
              if (outcome.metric == 'retention') {
                final before =
                    retentionProbe?.call(engine, bottleneck.node, engine.hours + horizon);
                final after = retentionProbe
                    ?.call(clone, bottleneck.node, clone.hours + horizon);
                if (before == null || after == null) {
                  entry.simulated = false;
                  entry.why = '未装载记忆模块，无法预测留存增益';
                } else {
                  entry.metric = 'retention';
                  entry.gain = FastEngine.round6(after - before);
                  entry.why = '${outcome.why}；${jsNumber(horizon)} 小时后的留存 '
                      '${FastEngine.round6(before)} → ${FastEngine.round6(after)}';
                }
              } else {
                for (var i = 0; i < params.simRounds && !clone.stopped; i += 1) {
                  clone.step();
                }
                final after = clone.reachability();
                entry.metric = 'reachability';
                entry.gain = FastEngine.round6(after - baselineReach);
                entry.why = '${outcome.why}；模拟 ${jsNumber(params.simRounds.toDouble())} 轮后'
                    '目标可达性 ${jsNumber(baselineReach)} → ${jsNumber(after)}';
              }
              if (entry.simulated) {
                entry.value = outcome.cost > 0
                    ? FastEngine.round6(entry.gain / outcome.cost)
                    : 0;
              }
            } else {
              entry.why = outcome.why;
            }
          } catch (error) {
            entry.why = '模拟失败：$error';
          }
        } else {
          entry.why = meta.simulatable
              ? '本次未模拟（sim_rounds=0）'
              : '该指令改变的是执行层用法，本引擎没有对应状态，未做模拟';
        }
        plan.add(entry);
      }
      // Keep at most the first three instructions per node: the list is meant to
      // be advice, not a catalogue.
      final forNode = plan.where((p) => p.node == bottleneck.node).toList();
      if (forNode.length > 3) {
        final keep = {
          for (final entry in forNode.take(3)) entry.instruction,
        };
        plan.removeWhere(
            (p) => p.node == bottleneck.node && !keep.contains(p.instruction));
      }
    }

    // Simulated entries first, then value, then gain - and stable, because ties
    // are common (all the rule-only entries score 0/0).
    _stableSortPlan(plan);
    return plan;
  }

  static void _stableSortPlan(List<FastPlanEntry> plan) {
    final indexed = [
      for (var i = 0; i < plan.length; i++) (index: i, entry: plan[i]),
    ];
    indexed.sort((x, y) {
      final a = x.entry;
      final b = y.entry;
      if (a.simulated != b.simulated) {
        return a.simulated ? -1 : 1;
      }
      if (b.value != a.value) {
        return b.value < a.value ? -1 : 1;
      }
      if (b.gain != a.gain) {
        return b.gain < a.gain ? -1 : 1;
      }
      return x.index.compareTo(y.index);
    });
    for (var i = 0; i < plan.length; i += 1) {
      plan[i] = indexed[i].entry;
    }
  }
}

/// Sorts [items] by a comparable key, keeping the original order for ties.
///
/// Dart's `List.sort` is not stable (it uses insertion sort for short lists and
/// dual-pivot quicksort beyond that), while JavaScript's `Array.prototype.sort`
/// has been stable since ES2019. Every order the JS publishes here can contain
/// ties, so a stable sort is part of matching the output, not a nicety.
void stableSortBy<T>(List<T> items, num Function(T item) key) {
  final indexed = [
    for (var i = 0; i < items.length; i++) (index: i, item: items[i]),
  ];
  indexed.sort((x, y) {
    final byKey = key(x.item).compareTo(key(y.item));
    return byKey != 0 ? byKey : x.index.compareTo(y.index);
  });
  for (var i = 0; i < items.length; i += 1) {
    items[i] = indexed[i].item;
  }
}

/// Formats a double the way JavaScript's `String(number)` does, for the display
/// strings the JS builds with template literals (`4`, not `4.0`).
///
/// The exponential-notation thresholds differ between the two languages for very
/// small/large magnitudes; those values do not occur in the vectors, and if one
/// ever does, the conformance test's exact string comparison will surface it
/// instead of letting it drift.
String jsNumber(double value) {
  if (value == value.roundToDouble() && value.abs() < 1e21) {
    return value.toInt().toString();
  }
  return value.toString();
}
